import type { Metadata } from "next";
import "./globals.css";
import { Cairo } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/Component/theme";
import ThemeProviderRTL from "@/Component/ThemeProviderRTL";
import { Stack } from "@mui/material";
import { getServerSession } from "next-auth";
import NextAuthSession from "@/Component/NextAuthSession";
import { authOptions } from "@/lib/authOptions";

const cairo = Cairo({
    weight: ["300", "400", "600", "700"],
    subsets: ["latin", "arabic"],
    display: "swap",
    variable: "--font-cairo",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerSession(authOptions) // Explicitly pass authOptions

    return (
        <html lang="en" dir="rtl">
            <head>
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
            </head>
            <body className={cairo.variable}>
                <NextAuthSession session={session}>
                    <ThemeProviderRTL>
                        <ThemeProvider theme={theme}>
                            <Stack height={"100%"}>
                                <Stack flexGrow={1} component={"main"}>
                                    {children}
                                </Stack>
                            </Stack>
                        </ThemeProvider>
                    </ThemeProviderRTL>
                </NextAuthSession>
            </body>
        </html>
    );
}
